# Generated by Django 5.0.5 on 2024-05-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
